services:
  # default configuration for services in *this* file
  _defaults:
    public: true

  App\Repository\Interfaces\ParticipantRepository:
    class: App\Repository\InMemory\InMemoryParticipantRepository

  App\Repository\Interfaces\CompanyRepository:
    class: App\Repository\InMemory\InMemoryCompanyRepository